<?php

declare(strict_types=1);

namespace PRSW\AmphpBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('amphp');

        $treeBuilder
            ->getRootNode()
            ->children()
            ->scalarNode('host')
            ->defaultValue('127.0.0.1')
            ->end()
            ->integerNode('port')
            ->defaultValue(8080)
            ->end()
            ->arrayNode('dbal')
            ->addDefaultsIfNotSet()
            ->children()
            ->integerNode('max_connections')
                ->info('Maximum number of MySQL connections in the pool (default: 100)')
                ->defaultValue(100)
            ->end()
            ->integerNode('idle_timeout')
            ->info('Seconds before an idle pooled connection is closed (default: 60)')
            ->defaultValue(60)
            ->end()
            ->integerNode('ping_interval')
            ->info('Seconds between connection keepalive pings (default: 30, 0 = ping every request)')
            ->defaultValue(30)
            ->min(0)
            ->end()
            ->end()
            ->end()
            ->integerNode('gc_interval')
            ->info('Seconds between PHP cycle collector runs (default: 30, 0 = disabled)')
            ->defaultValue(30)
            ->min(0)
            ->end()
            ->integerNode('max_requests')
            ->info('Number of requests handled by a single worker before restarting (default: 1000, 0 = never restart)')
            ->defaultValue(1000)
            ->min(0)
            ->end()
            ->integerNode('workers')
            ->info('Number of cluster worker processes (default: 0 = auto-detect CPU count)')
            ->defaultValue(0)
            ->min(0)
            ->end()
            ->integerNode('shutdown_timeout')
            ->info('Seconds for worker drain before force-shutdown when max-requests is reached (default: 5)')
            ->defaultValue(5)
            ->min(0)
            ->end()
            ->arrayNode('static_files')
            ->canBeDisabled()
            ->addDefaultsIfNotSet()
            ->children()
            ->scalarNode('public_dir')
            ->defaultNull()
            ->end()
            ->arrayNode('indexes')
            ->scalarPrototype()
            ->end()
            ->defaultValue(['index.html', 'index.htm'])
            ->end()
            ->integerNode('expires_period')
            ->info('Seconds before static file cache expiry (default: 604800 = 7 days)')
            ->defaultValue(604_800)
            ->min(0)
            ->end()
            ->end()
            ->end()
            ->arrayNode('tls')
            ->canBeEnabled()
            ->addDefaultsIfNotSet()
            ->children()
            ->scalarNode('cert_file')
            ->info('Absolute path to the PEM-encoded TLS certificate file (required when enabled)')
            ->defaultNull()
            ->end()
            ->scalarNode('key_file')
            ->info('Absolute path to the TLS private key file (defaults to cert_file)')
            ->defaultNull()
            ->end()
            ->scalarNode('passphrase')
            ->info('Passphrase for the TLS private key (if encrypted)')
            ->defaultNull()
            ->end()
            ->arrayNode('sni_certs')
            ->info('SNI certificates keyed by hostname')
            ->useAttributeAsKey('hostname')
            ->arrayPrototype()
            ->children()
            ->scalarNode('cert_file')->isRequired()->end()
            ->scalarNode('key_file')->defaultNull()->end()
            ->scalarNode('passphrase')->defaultNull()->end()
            ->end()
            ->end()
            ->end()
            ->enumNode('min_version')
            ->info('Minimum TLS version to negotiate')
            ->values(['TLSv1.0', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'])
            ->defaultValue('TLSv1.2')
            ->end()
            ->scalarNode('ciphers')
            ->info('OpenSSL cipher list string (colon-separated); null uses the default')
            ->defaultNull()
            ->end()
            ->integerNode('security_level')
            ->info('OpenSSL security level (0-5, requires OpenSSL >= 1.1.0)')
            ->min(0)->max(5)->defaultValue(2)
            ->end()
            ->arrayNode('alpn_protocols')
            ->info('ALPN protocol list (e.g. ["h2", "http/1.1"])')
            ->scalarPrototype()->end()
            ->defaultValue([])
            ->end()
            ->booleanNode('verify_peer')
            ->info('Enable peer certificate verification')
            ->defaultFalse()
            ->end()
            ->booleanNode('verify_peer_name')
            ->info('Enable peer name verification')
            ->defaultFalse()
            ->end()
            ->integerNode('verify_depth')
            ->info('Maximum certificate chain length')
            ->min(0)->defaultValue(10)
            ->end()
            ->scalarNode('ca_file')
            ->info('Path to the trusted CA certificate file')
            ->defaultNull()
            ->end()
            ->scalarNode('ca_path')
            ->info('Path to the trusted CA certificate directory')
            ->defaultNull()
            ->end()
            ->booleanNode('capture_peer')
            ->info('Capture peer certificate chain (accessible via TlsInfo)')
            ->defaultFalse()
            ->end()
            ->end()
            ->end()
            ->arrayNode('websocket')
            ->canBeEnabled()
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->info('Enable WebSocket server integration. When enabled, services implementing WebsocketClientHandler with the #[WebsocketEndpoint] attribute are automatically registered as WebSocket endpoints.')
            ->defaultValue(true)
            ->end()
            ->end()
            ->end()
            ->integerNode('request_timeout')
            ->info('Max time (seconds) for the full request/response cycle (default: 30, 0 = no timeout)')
            ->defaultValue(30)
            ->min(0)
            ->end()
            ->integerNode('header_timeout')
            ->info('Max time (seconds) to receive request headers (default: 10)')
            ->defaultValue(10)
            ->min(0)
            ->end()
            ->integerNode('body_timeout')
            ->info('Max time (seconds) to receive request body (default: 30)')
            ->defaultValue(30)
            ->min(0)
            ->end()
            ->integerNode('max_body_size')
            ->info('Max request body size in bytes (default: 10485760 = 10 MB, 0 = no limit)')
            ->defaultValue(10_485_760)
            ->min(0)
            ->end()
            ->arrayNode('readiness')
            ->canBeEnabled()
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('check_db')
                ->info('Enable DBAL readiness check (doctrine/dbal must be installed)')
                ->defaultValue(true)
                ->end()
            ->end()
            ->end()
            ->end();

        return $treeBuilder;
    }
}
